script improvement

diff --git a/.github/workflows/dev-prod-trigger-job.yml b/.github/workflows/dev-prod-trigger-job.yml
--- a/.github/workflows/dev-prod-trigger-job.yml
+++ b/.github/workflows/dev-prod-trigger-job.yml
@@ -59,8 +59,12 @@ jobs:
     - name: check dataset list
       run: |
         echo "${{vars.DATASETNAME}}-${{vars.DATASET_VERSION}}"
-        status=$(az ml data show --name ${{vars.DATASETNAME}} --version ${{vars.DATASET_VERSION}} --workspace-name ${{vars.MLWORKSPACE}} --resource-group ${{vars.RGNAME}})
+        status=$(az ml data show --name ${{vars.DATASETNAME}} --version ${{vars.DATASET_VERSION}} --workspace-name ${{vars.MLWORKSPACE}} --resource-group ${{vars.RGNAME}} 2>&1)
         echo "value of status is : $status"
+        if echo "$status" | grep -q "Asset with Asset ID was not found"; then
+          echo "Error: The dataset with the specified name and version was not found."
+          exit 1
+        fi
         created_at=$(echo "$status" | jq -r '.creation_context.created_at')
 
         echo "datecreate new: $created_at"
