added check

diff --git a/.github/workflows/dev-prod-trigger-job.yml b/.github/workflows/dev-prod-trigger-job.yml
--- a/.github/workflows/dev-prod-trigger-job.yml
+++ b/.github/workflows/dev-prod-trigger-job.yml
@@ -59,6 +59,12 @@ jobs:
     - name: check dataset list
       run: |
         echo "${{vars.DATASETNAME}}-${{vars.DATASET_VERSION}}"
+        if az ml data show --name ${vars.DATASETNAME} --version ${vars.DATASET_VERSION} --workspace-name ${vars.MLWORKSPACE} --resource-group ${vars.RGNAME}; then
+          echo "Dataset exists."
+        else
+          echo "Dataset not found."
+        exit 1
+        fi
         status=$(az ml data show --name ${{vars.DATASETNAME}} --version ${{vars.DATASET_VERSION}} --workspace-name ${{vars.MLWORKSPACE}} --resource-group ${{vars.RGNAME}} --query name -o tsv)
         echo "value of status is : $status"
         if echo "$status" | grep -q "Asset with Asset ID was not found"; then
