dataset check

diff --git a/.github/workflows/dev-prod-trigger-job.yml b/.github/workflows/dev-prod-trigger-job.yml
--- a/.github/workflows/dev-prod-trigger-job.yml
+++ b/.github/workflows/dev-prod-trigger-job.yml
@@ -59,7 +59,13 @@ jobs:
     - name: check dataset list
       run: |
         echo "${{vars.DATASETNAME}}-${{vars.DATASET_VERSION}}"
-        az ml data list --name ${{vars.DATASETNAME}} --workspace-name ${{vars.MLWORKSPACE}} --resource-group ${{vars.RGNAME}} --output table
+        # az ml data list --name ${{vars.DATASETNAME}} --workspace-name ${{vars.MLWORKSPACE}} --resource-group ${{vars.RGNAME}} --output table
+        if az ml data list --workspace-name ${{vars.MLWORKSPACE}} --resource-group ${{vars.RGNAME}} --output table | grep -q "${{vars.DATASETNAME}}"; then
+          echo "Dataset  exists."
+        else
+          echo "Dataset does not exist."
+          exit 1
+        fi
         echo "table tablelst"
         # if az ml data show --name ${{vars.DATASETNAME}} --version ${{vars.DATASET_VERSION}} --workspace-name ${{vars.MLWORKSPACE}} --resource-group ${{vars.RGNAME}}; then
         #   echo "Dataset exists."
@@ -67,24 +73,24 @@ jobs:
         #   echo "Dataset not found."
         # exit 1
         # fi
-        status=$(az ml data show --name ${{vars.DATASETNAME}} --version ${{vars.DATASET_VERSION}} --workspace-name ${{vars.MLWORKSPACE}} --resource-group ${{vars.RGNAME}} --debug)
-        echo "value of status is : $status"
-        if echo "$status" | grep -q "Asset with Asset ID was not found"; then
-          echo "Error: The dataset with the specified name and version was not found."
-          exit 3
-        fi
-        created_at=$(echo "$status" | jq -r '.creation_context.created_at')
+        # status=$(az ml data show --name ${{vars.DATASETNAME}} --version ${{vars.DATASET_VERSION}} --workspace-name ${{vars.MLWORKSPACE}} --resource-group ${{vars.RGNAME}} --debug)
+        # echo "value of status is : $status"
+        # if echo "$status" | grep -q "Asset with Asset ID was not found"; then
+        #   echo "Error: The dataset with the specified name and version was not found."
+        #   exit 3
+        # fi
+        # created_at=$(echo "$status" | jq -r '.creation_context.created_at')
 
-        echo "datecreate new: $created_at"
-        # echo "datecreate: $status.creation_context.created_at"
-        if [ -z "$created_at" ] || [ "$created_at" == "null" ]; then
-          echo "The created_at value is null or empty."
+        # echo "datecreate new: $created_at"
+        # # echo "datecreate: $status.creation_context.created_at"
+        # if [ -z "$created_at" ] || [ "$created_at" == "null" ]; then
+        #   echo "The created_at value is null or empty."
           
-          az ml data create --file dataset.yml --workspace-name ${{vars.MLWORKSPACE}} --resource-group ${{vars.RGNAME}}
+        #   az ml data create --file dataset.yml --workspace-name ${{vars.MLWORKSPACE}} --resource-group ${{vars.RGNAME}}
 
-        else
-          echo "The created_at value is: $created_at"
-        fi
+        # else
+        #   echo "The created_at value is: $created_at"
+        # fi
       env:
           DATASET_NAME: ${{ vars.DATASETNAME }}
           DBVERSION: ${{vars.DATASET_VERSION}}
